version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password123
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n123
      - GENERIC_TIMEZONE=Asia/Bangkok
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/tmp/workflows:ro
    depends_on:
      - postgres
      - redis
    networks:
      - lead_network

  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=leads_db
      - DB_USER=leads_user
      - DB_PASSWORD=leads123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AMOCRM_API_KEY=mock_key_123
      - TELEGRAM_API_ID=mock_api_id
      - TELEGRAM_API_HASH=mock_api_hash
      - TELEGRAM_SESSION_STRING=mock_session
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook
    volumes:
      - ./api/sessions:/app/sessions
    depends_on:
      - postgres
      - redis
    networks:
      - lead_network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lead_network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lead_network

volumes:
  n8n_data:
  postgres_data:
  redis_data:

networks:
  lead_network:
    driver: bridge